In [1]:
# 1.Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np
array = np.random.randint(1, 101, size=(3, 3))
transposed_array = array.T
import numpy as np

array = np.random.randint(1, 101, size=(3, 3))
transposed_array = array.T

print("Original array:")
print(array)
print("\nTransposed array:")
print(transposed_array)


Original array:
[[22 95 27]
 [69 13 87]
 [71 98 76]]

Transposed array:
[[22 69 71]
 [95 13 98]
 [27 87 76]]


In [3]:
# 2.  Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
import numpy as np
array_1d = np.arange(10)
array_2x5 = array_1d.reshape(2, 5)
array_5x2 = array_1d.reshape(5, 2)
import numpy as np

array_1d = np.arange(10)
array_2x5 = array_1d.reshape(2, 5)
array_5x2 = array_1d.reshape(5, 2)

print("Original 1D array:")
print(array_1d)
print("\nReshaped to 2x5:")
print(array_2x5)
print("\nReshaped to 5x2:")
print(array_5x2)


Original 1D array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [4]:
# Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
array_4x4 = np.random.rand(4, 4)
array_6x6 = np.zeros((6, 6))
array_6x6[1:5, 1:5] = array_4x4
import numpy as np

array_4x4 = np.random.rand(4, 4)
array_6x6 = np.zeros((6, 6))
array_6x6[1:5, 1:5] = array_4x4

print("Original 4x4 array:")
print(array_4x4)
print("\n6x6 array with border of zeros:")
print(array_6x6)



Original 4x4 array:
[[0.68017813 0.30697772 0.52654008 0.08837794]
 [0.16118047 0.61437914 0.22813161 0.41589992]
 [0.81423201 0.06956619 0.18921409 0.76547146]
 [0.82115591 0.66533345 0.72394405 0.37086032]]

6x6 array with border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.68017813 0.30697772 0.52654008 0.08837794 0.        ]
 [0.         0.16118047 0.61437914 0.22813161 0.41589992 0.        ]
 [0.         0.81423201 0.06956619 0.18921409 0.76547146 0.        ]
 [0.         0.82115591 0.66533345 0.72394405 0.37086032 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [6]:
#  Using NumPy, create an array of integers from 10 to 60 with a step of 5.

array = np.arange(10, 61, 5)
print(array)

[10 15 20 25 30 35 40 45 50 55 60]


In [7]:
# Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
#(uppercase, lowercase, title case, etc.) to each element.

# Create the array
arr = np.array(['python', 'numpy', 'pandas'])

# Uppercase
uppercase_arr = np.char.upper(arr)

# Lowercase
lowercase_arr = np.char.lower(arr)

# Title case
titlecase_arr = np.char.title(arr)

# Capitalize
capitalize_arr = np.char.capitalize(arr)

# Print the results
print("Original array:", arr)
print("Uppercase:", uppercase_arr)
print("Lowercase:", lowercase_arr)
print("Title case:", titlecase_arr)
print("Capitalize:", capitalize_arr)

Original array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title case: ['Python' 'Numpy' 'Pandas']
Capitalize: ['Python' 'Numpy' 'Pandas']


In [8]:
#  Generate a NumPy array of words. Insert a space between each character of every word in the array
arr = np.array(['python', 'numpy', 'pandas'])
spaced_arr = np.char.join(' ', arr)
print(spaced_arr)

['p y t h o n' 'n u m p y' 'p a n d a s']


In [9]:
#  Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Element-wise addition
addition = array1 + array2

# Element-wise subtraction
subtraction = array1 - array2

# Element-wise multiplication
multiplication = array1 * array2

# Element-wise division
division = array1 / array2

# Print the results
print("Array 1:\n", array1)
print("\nArray 2:\n", array2)
print("\nAddition:\n", addition)
print("\nSubtraction:\n", subtraction)
print("\nMultiplication:\n", multiplication)
print("\nDivision:\n", division)

Array 1:
 [[1 2 3]
 [4 5 6]]

Array 2:
 [[ 7  8  9]
 [10 11 12]]

Addition:
 [[ 8 10 12]
 [14 16 18]]

Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]

Multiplication:
 [[ 7 16 27]
 [40 55 72]]

Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [10]:
# Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.



identity_matrix = np.identity(5)
diagonal_elements = np.diag(identity_matrix)

print("Identity Matrix:")
print(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)

Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [11]:
#  Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
#this array.

def is_prime(n):
  if n <= 1:
    return False
  for i in range(2, int(n**0.5) + 1):
    if n % i == 0:
      return False
  return True

# Generate array of random integers
random_array = np.random.randint(0, 1001, size=100)

# Find prime numbers
prime_numbers = [num for num in random_array if is_prime(num)]

# Display prime numbers
print("Random Array:", random_array)
print("\nPrime Numbers in the Array:", prime_numbers)

Random Array: [ 386  794  791  613  185  352  873   94  485  881  307  352  920  590
  392  821  176  950  316  121  967  306  273  488  787  745  178  518
  406  290  859   35  847  608  447  420  410  833  540  867  483  347
  952  593  798  790   81  941  326  513  189  929  689  722  768  528
  560  240  875  806  986  421  643  108  816  214  983   22  836  266
  579  155   18 1000  176  208  692  200  731  973  692  471  589  877
  511  163  199  914  774  685  325  437  224  568  560  880  206  377
  442  973]

Prime Numbers in the Array: [613, 881, 307, 821, 967, 787, 859, 347, 593, 941, 929, 421, 643, 983, 877, 163, 199]


In [13]:
#  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
#averages


# Assume 30 days in the month
daily_temperatures = np.random.randint(20, 35, size=30)

# Reshape into weeks (assuming each week has 7 days)
# Calculate the number of full weeks
num_full_weeks = len(daily_temperatures) // 7

# Reshape only the full weeks' data
weekly_temperatures = daily_temperatures[:num_full_weeks * 7].reshape(-1, 7)

# Calculate weekly averages for full weeks
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Display results
print("Daily Temperatures:", daily_temperatures)
print("\nWeekly Temperatures:\n", weekly_temperatures)
print("\nWeekly Averages:", weekly_averages)

Daily Temperatures: [20 27 25 34 29 33 31 21 26 31 24 26 25 20 24 33 32 32 34 22 31 34 29 34
 21 28 23 31 23 23]

Weekly Temperatures:
 [[20 27 25 34 29 33 31]
 [21 26 31 24 26 25 20]
 [24 33 32 32 34 22 31]
 [34 29 34 21 28 23 31]]

Weekly Averages: [28.42857143 24.71428571 29.71428571 28.57142857]
